import Script from "next/script";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import 'bootstrap/dist/css/bootstrap.css'
import "@/styles/globals.css";

export const metadata = {
  title: "Business Direction",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="">
        <header>
          <Navbar />
        </header>
        {children}
        <Footer/>
        <Script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"
      />
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"
      />
      </body>
    </html>
  );
}
