import Head from "next/head";
import { Image } from "react-bootstrap";
import styles from "@/styles/Home.module.css";
import { cursosHome } from "@/constants";

export default function Home() {
  return (
    <>
      <Head>
        <title> Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="banner">
    <h1>Alcance o Sucesso com as Estratégias Certas.</h1>
   </section>
<section className="subtitulo">
   <h1 className="text-center">Um pouco sobre nossos cursos:</h1>
  </section>
      <main className="container-fluid my-2">
        <div className="container row row-cols-1 row-cols-md-3 row-gap-4 p-0 mx-auto">
          {cursosHome.map((curso) => (
            <div className="col" key={curso.titulo}>
              <div className="card h-100">
                <div className="card-img-top card-img-home ">
                  <Image
                    src={curso.srcUrl}
                    alt={curso.altText}
                    //width={454}
                    //Height={280}
                    //fill
                    //objectFit="cover"
                    fluid
                  />
                </div>
                <div className="card-body">
                  <h5 className="card-title">{curso.titulo}</h5>
                  <p className="card-text">{curso.descricao}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
        <div>
          <br />
          <br />
          <br />
        </div>
        <section className="entre">
          <h2 style={{ textAlign: "center" }}>
            Temos uma equipe competente esperando por você, <br />
            faça sua inscrição e tenha todo apoio e orientação necessária <br />{" "}
            para seu negócio dar certo!
            <br />
            <br />
          </h2>
        </section>
        <div style={{ textAlign: "center" }}>
          <button
            className="btn btn-primary"
            style={{
              height: 50,
              fontSize: 20,
              fontFamily: '"Rubik", sans-serif',
            }}
          >
            Entrar
          </button>
        </div>
        <div>
          <br />
          <br />
        </div>
      </main>
    </>
  );
}
